commands:
  help:
    #disabled: true
    commandName: "help"
    description: "View a list of all commands"
    options:
      dmPermission: false
      #descriptionLocalization:
      #descriptionInLocale:
      #descriptionLocalizations:
      #nameLocalization:
      #nameInLocale:
      #nameLocalizations:
    response:
      ephemeral: true