commands:
  help:
    commandList:
      # ------
      # 
      # PLACEHOLDERS:
      # {commands} - List of all commands, formatted
      #
      # ------
      title: "Commands:"
      description: "{commands}"
    